### ISSUE TITLE
There is no support of search in type "SET"

### ISSUE THREAD

**Issue by evinlort** [Oktopost/Squid#5]
As per https://dev.mysql.com/doc/refman/8.0/en/set.html

> Normally, you search for SET values using the FIND_IN_SET() function or the LIKE operator:

mysql> SELECT * FROM tbl_name WHERE FIND_IN_SET('value',set_col)>0;
mysql> SELECT * FROM tbl_name WHERE set_col LIKE '%value%';
The first statement finds rows where set_col contains the value set member. The second is similar, but not the same: It finds rows where set_col contains value anywhere, even as a substring of another set member.

The following statements also are permitted:

mysql> SELECT * FROM tbl_name WHERE set_col & 1;
mysql> SELECT * FROM tbl_name WHERE set_col = 'val1,val2';
The first of these statements looks for values containing the first set member. The second looks for an exact match. Be careful with comparisons of the second type. Comparing set values to 'val1,val2' returns different results than comparing values to 'val2,val1'. You should specify the values in the same order they are listed in the column definition.

To determine all possible values for a SET column, use SHOW COLUMNS FROM tbl_name LIKE set_col and parse the SET definition in the Type column of the output.

**Comment by alexey-pkv** [comment]
Squid is not designed to directly provide support for a specific MySQL function. Instead you should be using the `where` method under `IQuery` interface. 

Like this:

```
$mysql = new Squid\MySql();
$conn = $mysql->getConnector();

$conn
    ->select()
    ->from('tbl_name')
    ->where('FIND_IN_SET(?, set_col) > 0', ['value'])
    ->query();

// or
		
$conn
    ->select()
    ->from('tbl_name')
    ->where('set_col & 1')
    ->query();
```
Is this what you are trying to do? If not, can you please provide the final MySQL query you are trying to generate?

Please note that you can use `assemble` and  `bind` methods to debug the query:
```
$sqlString  = $conn->select()
    ->from('tbl_name')
    // ... setup ...
    ->assemble();

$bindParams  = $conn->select()
    ->from('tbl_name')
    // ... setup ...
    ->bind();

var_dump($sqlString, $bindParams);
```
