### ISSUE TITLE
unhandled server gone away warning

### ISSUE THREAD

**Issue by daddyz** [Oktopost/Squid#6]
PHP Warning:  Error while sending QUERY packet. PID=3124820 in ..../vendor/oktopost/squid/src/Squid/MySql/Impl/Connection/MySqlConnection.php on line 127

set wait_timeout and interactive_timeout to low values and execute query in a loop with sleeps more than wait timeout

**Comment by alexey-pkv** [comment]
There are 2 ways to handle this exception. 

The first one is to close the connection before executing a query. Also if you are executing a repetative and long task in a loop, it may make sence to close the connection at the end or start of each loop.

Example:
```
$mysql = new MySql();
$mysql->config()->addConfig('main', ['host' => 'localhost', 'user' => 'root']);

$conn = $mysql->getConnector();

for ($i = 0; $i < 100; $i++)
{
    $conn->close();

    $select = $conn->select();
    $res = $select
        ->columnsExp('1')
        ->queryAll();

    sleep(2);
}
```

To clarify, Squid will open a connection when a query needs to be executed and the current connection is closed. So it's completly safe to close the connection at any point (excluding in the middle of a cursor loop or transaction).

The second option can be to add a decorator and reconnect when this spusific error is encountered:

```
class ReconnectDecorator extends MySql\Connection\AbstractMySqlExecuteDecorator
{
    private MySql $m;
    
    public function __construct(MySql $m)
    {
        $this->m = $m;
    }
    
    
    public function execute(string $cmd, array $bind = [])
    {
        try
        {
            return $this->child()->execute($cmd, $bind);
        }
        catch (\Throwable $t)
        {
            if (strpos($t->getMessage(), '... the text...') /* or by code*/)
            {
                $this->m->getConnector('main')->close();
                return $this->child()->execute($cmd, $bind);
            }
            else
            {
                throw $t;
            }
        }
    }
}

$mysql = new MySql();
$mysql->config()->addExecuteDecorator(new ReconnectDecorator($mysql));
```
